# Generated by Django 4.0.2 on 2022-05-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(unique=True)),
                ('admUsuario', models.CharField(max_length=50)),
                ('admPassword', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=60)),
                ('apellidosCliente', models.CharField(max_length=50)),
                ('estadoCliente', models.CharField(max_length=50)),
                ('telefonoCliente', models.IntegerField()),
                ('correoCliente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioRol', models.CharField(max_length=50)),
                ('usuarioLogin', models.CharField(max_length=50)),
                ('usuarioPassword', models.CharField(max_length=50)),
                ('usuarioEstado', models.CharField(max_length=50)),
            ],
        ),
    ]
