# Generated by Django 4.0.2 on 2022-05-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInmobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoInmueble', models.CharField(max_length=50)),
                ('descripcionInmueble', models.CharField(max_length=50)),
                ('precioInmueble', models.IntegerField()),
                ('ciudadInmueble', models.CharField(max_length=50)),
                ('barrioInmueble', models.CharField(max_length=50)),
                ('tipoNegocios', models.CharField(max_length=50)),
                ('imagenInmueble', models.CharField(max_length=50)),
                ('tituloInmueble', models.CharField(max_length=50)),
                ('fechaInmueble', models.DateTimeField()),
            ],
        ),
    ]
