# Generated by Django 4.2.3 on 2023-07-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInmobiliaria', '0003_persona_roles_solicitud_delete_administrador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='imagenInmueble',
            field=models.FileField(blank=True, null=True, upload_to='Fotos/'),
        ),
    ]
