# Generated by Django 4.2.3 on 2023-07-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInmobiliaria', '0004_alter_inmueble_imageninmueble'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='ciudadInmueble',
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='estadoInmueble',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=50),
        ),
    ]
