# Generated by Django 4.2.3 on 2023-07-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appInmobiliaria', '0005_remove_inmueble_ciudadinmueble_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='tituloInmueble',
            new_name='nombreInmueble',
        ),
    ]
