# Generated by Django 4.2.3 on 2023-07-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInmobiliaria', '0006_rename_tituloinmueble_inmueble_nombreinmueble'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='barrioInmueble',
            new_name='direccionInmueble',
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipoInmueble',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Local', 'Local'), ('Oficina', 'Oficina'), ('Bodega', 'Bodega'), ('Lote', 'Lote'), ('Finca', 'Finca')], max_length=50),
        ),
    ]
